
using System;
using System.Collections.Generic;

namespace resolucion_parcial
{
	public class Lugar
	{
		public Dictionary<string, string> paisesISO = new Dictionary<string, string>()
		{
		    { "Angola", "AGO" },
		    { "Argelia", "DZA" },
		    { "Benin", "BEN" },
		    { "Botswana", "BWA" },
		    { "Burkina Faso", "BFA" },
		    { "Burundi", "BDI" },
		    { "Cabo Verde", "CPV" },
		    { "Camerún", "CMR" },
		    { "Chad", "TCD" },
		    { "Comoras", "COM" },
		    { "Congo", "COG" },
		    { "Côte d'Ivoire", "CIV" },
		    { "Djibouti", "DJI" },
		    { "Egipto", "EGY" },
		    { "Eritrea", "ERI" },
		    { "Etiopía", "ETH" },
		    { "Gabón", "GAB" },
		    { "Gambia", "GMB" },
		    { "Ghana", "GHA" },
		    { "Guinea", "GIN" },
		    { "Guinea Bissau", "GNB" },
		    { "Guinea Ecuatorial", "GNQ" },
		    { "Kenya", "KEN" },
		    { "Lesotho", "LSO" },
		    { "Liberia", "LBR" },
		    { "Libia", "LBY" },
		    { "Madagascar", "MDG" },
		    { "Malawi", "MWI" },
		    { "Malí", "MLI" },
		    { "Marruecos", "MAR" },
		    { "Mauricio", "MUS" },
		    { "Mauritania", "MRT" },
		    { "Mozambique", "MOZ" },
		    { "Namibia", "NAM" },
		    { "Níger", "NER" },
		    { "Nigeria", "NGA" },
		    { "República Centroafricana", "CAF" },
		    { "Senegal", "SEN" },
		    { "Seychelles", "SYC" },
		    { "Sierra Leona", "SLE" },
		    { "Somalia", "SOM" },
		    { "Sudáfrica", "ZAF" },
		    { "Sudán", "SDN" },
		    { "Sudán del Sur", "SSD" },
		    { "Swazilandia", "SWZ" },
		    { "Tanzanía", "TZA" },
		    { "Togo", "TGO" },
		    { "Túnez", "TUN" },
		    { "Uganda", "UGA" },
		    { "Zambia", "ZMB" },
		    { "Zimbabwe", "ZWE" },
		    { "Antigua y Barbuda", "ATG" },
		    { "Argentina", "ARG" },
		    { "Aruba", "ABW" },
		    { "Bahamas", "BHS" },
		    { "Barbados", "BRB" },
		    { "Belice", "BLZ" },
		    { "Bolivia", "BOL" },
		    { "Bolivia, zona franca Winner", "BOL" },
		    { "Brasil", "BRA" },
		    { "Brasil, zona franca Manaos", "BRA" },
		    { "Canadá", "CAN" },
		    { "Chile", "CHL" },
		    { "Colombia", "COL" },
		    { "Costa Rica", "CRI" },
		    { "Cuba", "CUB" },
		    { "Dominica", "DMA" },
		    { "Ecuador", "ECU" },
		    { "El Salvador", "SLV" },
		    { "Estados Unidos", "USA" },
		    { "Granada", "GRD" },
		    { "Guatemala", "GTM" },
		    { "Guyana", "GUY" },
		    { "Haití", "HTI" },
		    { "Honduras", "HND" },
		    { "Jamaica", "JAM" },
		    { "México", "MEX" },
		    { "Nicaragua", "NIC" },
		    { "Panamá", "PAN" },
		    { "Paraguay", "PRY" },
		    { "Perú", "PER" },
		    { "Puerto Rico", "PRI" },
		    { "República Dominicana", "DOM" },
		    { "San Cristóbal y Nevis", "KNA" },
		    { "San Vicente y Las Granadinas", "VCT" },
		    { "Santa Lucía", "LCA" },
		    { "Suriname", "SUR" },
		    { "Trinidad y Tobago", "TTO" },
		    { "Uruguay", "URY" },
		    { "Venezuela", "VEN" },
		    { "Antillas Holandesas", "ANT" },
		    { "Afganistán", "AFG" },
		    { "Arabia Saudita", "SAU" },
		    { "Armenia", "ARM" },
		    { "Azerbaiyán", "AZE" },
		    { "Bahrein", "BHR" },
		    { "Bangladesh", "BGD" },
		    { "Bhután", "BTN" },
		    { "Brunei", "BRN" },
		    { "Camboya", "KHM" },
		    { "China", "CHN" },
		    { "Corea", "KOR" },
		    { "Corea Democrática y Popular", "PRK" },
		    { "Emiratos Árabes Unidos", "ARE" },
		    { "Filipinas", "PHL" },
		    { "Georgia", "GEO" },
		    { "India", "IND" },
		    { "Indonesia", "IDN" },
		    { "Irán", "IRN" },
		    { "Iraq", "IRQ" },
		    { "Israel", "ISR" },
		    { "Japón", "JPN" },
		    { "Jordania", "JOR" },
		    { "Kazajstán", "KAZ" },
		    { "Kirguistán", "KGZ" },
		    { "Kuwait", "KWT" },
		    { "Laos", "LAO" },
		    { "Líbano", "LBN" },
		    { "Malasia", "MYS" },
		    { "Maldivas", "MDV" },
		    { "Mongolia", "MNG" },
		    { "Myanmar", "MMR" },
		    { "Nepal", "NPL" },
		    { "Omán", "OMN" },
		    { "Pakistán", "PAK" },
		    { "Palestina", "PSE" },
		    { "Qatar", "QAT" },
		    { "Singapur", "SGP" },
		    { "Siria", "SYR" },
		    { "Sri Lanka", "LKA" },
		    { "Tailandia", "THA" },
		    { "Taiwan", "TWN" },
		    { "Tayikistán", "TJK" },
		    { "Timor Leste", "TLS" },
		    { "Turkmenistán", "TKM" },
		    { "Uzbekistán", "UZB" },
		    { "Viet Nam", "VNM" },
		    { "Yemen", "YEM" },
		    { "Albania", "ALB" },
		    { "Alemania", "DEU" },
		    { "Andorra", "AND" },
		    { "Austria", "AUT" },
		    { "Belarús", "BLR" },
		    { "Bélgica", "BEL" },
		    { "Bosnia y Herzegovina", "BIH" },
		    { "Bulgaria", "BGR" },
		    { "Chipre", "CYP" },
		    { "Croacia", "HRV" },
		    { "Dinamarca", "DNK" },
		    { "Eslovaquia", "SVK" },
		    { "Eslovenia", "SVN" },
		    { "España", "ESP" },
		    { "Estonia", "EST" },
		    { "Finlandia", "FIN" },
		    { "Francia", "FRA" },
		    { "Grecia", "GRC" },
		    { "Hungría", "HUN" },
		    { "Irlanda", "IRL" },
		    { "Islandia", "ISL" },
		    { "Italia", "ITA" },
		    { "Letonia", "LVA" },
		    { "Liechtenstein", "LIE" },
		    { "Lituania", "LTU" },
		    { "Luxemburgo", "LUX" },
		    { "Macedonia", "MKD" },
		    { "Malta", "MLT" },
		    { "Moldova", "MDA" },
		    { "Mónaco", "MCO" },
		    { "Montenegro", "MNE" },
		    { "Noruega", "NOR" },
		    { "Países Bajos", "NLD" },
		    { "Polonia", "POL" },
		    { "Portugal", "PRT" },
		    { "Reino Unido de Gran Bretaña e Irlanda del Norte", "GBR" },
		    { "República Checa", "CZE" },
		    { "Rumania", "ROU" },
		    { "Rusia", "RUS" },
		    { "San Marino", "SMR" },
		    { "Serbia", "SRB" },
		    { "Suecia", "SWE" },
		    { "Suiza", "CHE" },
		    { "Turquía", "TUR" },
		    { "Ucrania", "UKR" },
		    { "Vaticano", "VAT" },
		    { "Australia", "AUS" },
		    { "Fiji", "FJI" },
		    { "Islas Marianas", "MNP" },
		    { "Islas Marshall", "MHL" },
		    { "Islas Salomón", "SLB" },
		    { "Kiribati", "KIR" },
		    { "Micronesia", "FSM" },
		    { "Nauru", "NRU" },
		    { "Nueva Zelanda", "NZL" },
		    { "Palaos", "PLW" },
		    { "Papúa Nueva Guinea", "PNG" },
		    { "Samoa", "WSM" },
		    { "Tonga", "TON" },
		    { "Tuvalu", "TUV" },
		    { "Vanuatu", "VUT" }
		};
		
		public Lugar()
		{
		}
		
		public string ObtenerCodigoISO(string pais)
		{
		    string codigoISO = "";
		    paisesISO.TryGetValue(pais, out codigoISO);
		    return codigoISO;
		}

	}
}
